### ISSUE TITLE
Farmer's Delight Refabricated Compat

### ISSUE THREAD

**Issue by aninusmuffin** [ianm1647/farmersknives#18]
There is a new fabric port of Farmer's Delight by Pug and MehVahdJukaar. ([Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated))

This version is closer to the original Forge version of the mod, making porting addons to forge/fabric easier.
 I think it would be nice if there was support for this version to since Supplementaries only supports this version from now on.

**This is from the mod's page**
> Q. How does this different from the other existing Farmer's Delight Fabric?
>
>A. This port's main focus has been on simplicity and faithfulness to the original mod. This meant that only minor changes were made to accommodate the loader specific things.
>
>Package names and all existing behavior has been kept the same. This means that FD addons can now easily be ported from Forge to Fabric with, ideally, no change at all as all the package names are the same.
>
>[A list of differences can be found here.](https://gist.github.com/MerchantPug/f71b4d89272f8dc3757f4cec723617c0)

**Comment by ianm1647** [comment]
tis ported
