### ISSUE TITLE
Fiery Knife for twilight forest is crafted with a single stick

### ISSUE THREAD

**Issue by AllyJaxx** [ianm1647/farmersknives#6]
I'd assume this is meant to be crafted with a stick and a fiery ingot, but it only takes a stick for some reason?

![image](https://user-images.githubusercontent.com/64360185/209883826-380972c8-b256-4db8-9241-c5b0ef899c9f.png)
![image](https://user-images.githubusercontent.com/64360185/209883885-3f22d69a-011a-448f-be74-7566d0c86d1d.png)
![image](https://user-images.githubusercontent.com/64360185/209883933-df087bf5-3f9d-4621-91c2-e7cc2baae5a9.png)

**Comment by ianm1647** [comment]
what version is this for, i have an update for 1.19 but if its needed on 1.18 as well i would love to know

**Comment by AllyJaxx** [comment]
Was on 1.19, untested on 1.18

**Comment by ianm1647** [comment]
okay well 1.19 is fixed so that problem should be gone

**Comment by Sunconure11** [comment]
I have a similar issue on 1.19.2, but with star platinum knives.

![image](https://github.com/ianm1647/farmersknives/assets/5614902/29db1f30-9bdc-44a8-af4e-4e796e008a23)
